name: CI for Climate Insights

# TODO: Define workflow to run in pull requests and pushes to the main branch.
on:

jobs:
  build:
    # TODO: Specify the runner environment to latest ubuntu..

    steps:
    # TODO: Checkout the repository code.

    # TODO: Set up the required programming language environment.
    # For Python, this involves selecting the Python version.
    - name: Set up Python
 
    # TODO: Install project dependencies.
    - name: Install dependencies
  
    # TODO: Implement a code style check (linting).
    # Example: flake8 <source_directory> <test_directory>
    - name: Check code style

    # TODO: Run automated tests.
    # This is a critical step to ensure code correctness.
    - name: Run tests
      # TODO: Set up PYTHONPATH environment variable for tests.
      env:
         # environment variable to include the source directory.        
      # Write the command to run tests.

    # TODO: Execute the "analyze.py <input_csv> <output_file>" script.
    # In this case, it's generating a plot.
    # Ensure input and output paths are correct.
    - name: Generate climate report plot
  
    # TODO: Upload build artifacts.
    # This makes build outputs (like plots or reports) available after the workflow runs.
    - name: Upload plot artifact
      uses:
      with:
        # Name the artifact to climate-plot.
        name: 
        # Specify the path to the artifact to output directory and file name is plot.png.
        path: 
